name: Docker CI/CD with Tests

on:
  push:
    branches:
      - main

jobs:
  docker-test-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t fastapi-app .

      - name: Run tests inside Docker
        run: docker run fastapi-app pytest

      - name: Run Docker container
        run: docker run -d -p 8000:8000 fastapi-app